# Assignment 4

Due: October 8, 2024

Name: Eric Wu

In [70]:
import sys
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive


In [71]:
sys.path.append('/content/drive/MyDrive/Colab Notebooks/CDS411')

In [72]:
import numpy as np
import shakespeare
import yin13

## Problem 1
Given below are the counts for the first five positions of the sentences from "Mr. Raspberry" by H. W. Monroe.  The text was split into its sentences, and the occurrences of the first five letters were counted, but only a few are shown.  The first row of data goes with the first position in the sentences.  This shows that the most popular first letter was actually a double-quote, and it was seen 1162 times.  The second most popular letter was a 't' (328 times).  For the second position in the sentences, the most popular letter was 'h' (539 times) and the second most popular was 'y' (304 times).  Using this data, draw an emission hidden Markov model (HMM) with the probabilities of emission.

In [73]:
### answer

inpt = np.array([[('\"', 1162), ('t', 328), ('s', 199), ('k', 178), ('a', 122)], [('h', 539), ('y', 304), ('i', 209), ('a', 172), ('w', 167)],[('e', 629), ('o', 317), ('h', 299), (' ', 229), ('l', 214)],[(' ', 600), ('i', 308), ('e', 218), ('a', 188), ('n', 118)],[(' ', 466), ('e', 381), ('t', 202), ('h', 136), ('d', 115)]])
#print(inpt.shape)

hmm = {}
counter = 1

for r in range(len(inpt[:,0,0])):
  smm = 0
  for c in range(len(inpt[r,:,:])):
    smm+=int(inpt[r,c,1])

  temp = []
  for c in range(len(inpt[r,:,:])):
    temp.append((str(inpt[r,c,0]),int(inpt[r,c,1])/smm))

  if counter == len(inpt[:,0,0]):
    temp.append(-1)
  else:
    temp.append(counter)

  hmm[r] = temp
  counter += 1



In [74]:
def EMatch( hmmi, letter ):
  hit = (-1,-1)
  for i in hmmi[0]:
    if letter == i[0]:
      hit=i
      break
  return hit

def EProb( hmm, instr ):
  L = len( instr )
  k = 0
  pbs = 1.0
  for i in range( L ):
    emit = EMatch( hmm[k], instr[i] )
    pbs *= emit[1]
    k = hmm[k][1]
  return pbs

In [76]:
print(hmm)

#EProb(hmm, 'tyoie')

{0: [('"', 0.5842131724484666), ('t', 0.1649069884364002), ('s', 0.10005027652086476), ('k', 0.08949220713926596), ('a', 0.06133735545500251), 1], 1: [('h', 0.38749101365923794), ('y', 0.21854780733285406), ('i', 0.15025161754133717), ('a', 0.12365204888569374), ('w', 0.12005751258087707), 2], 2: [('e', 0.3726303317535545), ('o', 0.1877962085308057), ('h', 0.17713270142180096), (' ', 0.13566350710900474), ('l', 0.12677725118483413), 3], 3: [(' ', 0.41899441340782123), ('i', 0.21508379888268156), ('e', 0.15223463687150837), ('a', 0.13128491620111732), ('n', 0.0824022346368715), 4], 4: [(' ', 0.35846153846153844), ('e', 0.29307692307692307), ('t', 0.15538461538461537), ('h', 0.10461538461538461), ('d', 0.08846153846153847), -1]}


## Problem 2
Using the same manuscript, the following is a list of some of the popular transitions for a 1-mer.  For example, the letter 'a' followed the letter 't' is seen 957 times.  The letter 't' followed the letter 'h' is seen 652 times.  From this data, draw a transition HMM using probabilities.  Some transitions such as 'k' to 't' were not seen in the manuscript.  Determine the $4 \times 4$ matrix of transition probabilities for the alphabet 'takh'.

In [ ]:
inpt = np.array(['t','t',630,'t','a',957,'t','h',10899,'k','k',1,'k','a',8,'k','h',1,'a','t',2978,'a','k',328,'a','a',9,'a','h',69,'h','t',652,'h','a',3127,'h','h',23])

inpt = np.insert(inpt,1*3,np.array(['t','k',0]))
inpt = np.insert(inpt,4*3,np.array(['k','t',0]))
inpt = np.insert(inpt,14*3,np.array(['h','k',0]))
inpt = inpt.reshape(16,3)
print(inpt)

matx = np.int32(inpt[:,2].reshape(4,4))
print(matx)

''' Matx headers

  t k a h
t
k
a
h
'''

row_smm = np.sum(matx,axis=1)

matx = matx/row_smm[:,np.newaxis]
print(matx)

print(np.sum(matx[3,:]))

[['t' 't' '630']
 ['t' 'k' '0']
 ['t' 'a' '957']
 ['t' 'h' '10899']
 ['k' 't' '0']
 ['k' 'k' '1']
 ['k' 'a' '8']
 ['k' 'h' '1']
 ['a' 't' '2978']
 ['a' 'k' '328']
 ['a' 'a' '9']
 ['a' 'h' '69']
 ['h' 't' '652']
 ['h' 'a' '3127']
 ['h' 'k' '0']
 ['h' 'h' '23']]
[[  630     0   957 10899]
 [    0     1     8     1]
 [ 2978   328     9    69]
 [  652  3127     0    23]]
[[0.05045651 0.         0.07664584 0.87289765]
 [0.         0.1        0.8        0.1       ]
 [0.88002364 0.09692671 0.00265957 0.02039007]
 [0.17148869 0.82246186 0.         0.00604945]]
0.9999999999999999


## Problem 3
Using the data in the previous problem, determine the $4 \times 4$ odds matrix for the alphabet 'takh'.

In [ ]:
# your code and print answer
''' Matx headers

  t k a h
t
k
a
h
'''
print(matx)


prob = matx[2,0]*matx[1,2]*matx[3,1]
print(f'The probibility is {prob}')

[[0.05045651 0.         0.07664584 0.87289765]
 [0.         0.1        0.8        0.1       ]
 [0.88002364 0.09692671 0.00265957 0.02039007]
 [0.17148869 0.82246186 0.         0.00604945]]
The probibility is 0.5790287058074449


## Problem 4
Using the data from the previous problem, determine the $4 \times 4$ log-odds matrix for the alphabet 'takh'. (Use the natural log function.) (It is possible that you will get a warning because Python attempted to compute the log(0).  Ignore those warnings.)

In [ ]:
############# your code and print numerical answer
matx_log = np.log(matx/0.25)

prob = matx_log[2,0]*matx_log[1,2]*matx_log[3,1]

print(f'The probibility is {prob}')

The probibility is 1.7431666390550524


<ipython-input-60-8c5573cda648>:2: RuntimeWarning: divide by zero encountered in log
  matx_log = np.log(matx/0.25)


In [ ]:
prob = matx_log[2,0]+matx_log[1,2]+matx_log[3,1]

print(f'The probibility is {prob}')

The probibility is 3.6124798589727694


## Problem 5
Using the 'sonnets.txt' data, what is the most popular 7-mer?

In [ ]:
#############  Your code and print answer
from collections import Counter

sonnets = shakespeare.Read('/content/drive/MyDrive/Colab Notebooks/CDS411/sonnets.txt')

In [ ]:
cntd = Counter([sonnets[i:i+7] for i in range(len(sonnets)-7)]) #Create list of 7-mers, then use the counter object to get counts of ea unique 7mer

In [ ]:
print(cntd.most_common(1)) #output most common count

[(' beauty', 67)]


## Problem 6
Using the 'sonnets.txt' data what are the characters and their counts that follow the 7-mer ' beauty' (space before the b)?

In [ ]:
# your code and print answer
phrase = ' beauty' #fixed the phrase, misread the question as 'beauty ' lol

dct = shakespeare.MakeDict(sonnets,7)
print(dct[phrase])

[["'", ' ', ','], array([0.25373134, 0.68656716, 0.05970149])]


## Problem 7
In the DNA HMM (Yin's work), we computed several matrices in front of the start codon.  Repeat this experiment for the first 30,000 sequences in the 'start.txt' file.  Show the first matrix of probability values.


In [ ]:
###########3  your code and print answer

starts_path = '/content/drive/MyDrive/Colab Notebooks/CDS411/starts.txt'

with open(starts_path) as f:
        data = f.read().splitlines()

probs, logodds = yin13.BuildHMM(data)

print(probs[0,:])

[[0.35309641 0.11206897 0.3690183  0.16581633]
 [0.32264231 0.19286321 0.2693288  0.21516568]
 [0.3498143  0.10886722 0.41272052 0.12859796]
 [0.30158033 0.13740123 0.26412057 0.29689786]]


## Problem 8
In the Yin DNA problem, we computed several $4 \times 4$ matrices.  Compute the standard deviation of the values in each matrix. (One theory is that the matrix with the largest standard deviation contains the most information needed for the HMM to produce the correct answer.)

In [ ]:
'''print(probs.shape)

test = probs[:2,:,:]
print(test)

test = test.reshape(2,16)
print(test)'''

'print(probs.shape)\n\ntest = probs[:2,:,:]\nprint(test)\n\ntest = test.reshape(2,16)\nprint(test)'

In [ ]:
# your code and print answer
n, r, c = probs.shape

probs_arr = probs.reshape(n,r*c)

deviations = probs_arr.std(axis=1)
print(deviations)

[0.09678269 0.12392972 0.11663626 0.12121758 0.09622485 0.07065431
 0.06834339 0.0646014  0.0681519  0.07044993 0.05638101 0.07578825
 0.43278541 0.21647888 0.21647888 0.06655442 0.10966758 0.06692634]


In [ ]:
ndx_max = np.argmax(deviations)
mat_max = probs[ndx_max,:,:]
print(mat_max)

[[9.99630405e-01 1.23198226e-04 1.23198226e-04 1.23198226e-04]
 [9.99676689e-01 1.07770234e-04 1.07770234e-04 1.07770234e-04]
 [9.99473407e-01 1.75530981e-04 1.75530981e-04 1.75530981e-04]
 [9.99644760e-01 1.18413262e-04 1.18413262e-04 1.18413262e-04]]


## Problem 9
In a previous problem, the $4 \times 4$ matrices were computed, and the first one was shown.  Compute the odds values for this matrix.


In [ ]:
# your code and print answer
prob1 = probs[0,:,:]

odds = prob1/0.25
print(odds)

[[1.41238564 0.44827586 1.47607319 0.66326531]
 [1.29056924 0.77145285 1.07731521 0.8606627 ]
 [1.3992572  0.4354689  1.65088208 0.51439183]
 [1.20632133 0.54960492 1.05648229 1.18759145]]


## Problem 10
Using the information from the previous problem, compute the log-odds values for the matrix.  (use the natural log.)

In [ ]:
# your code and print answer
log_odds = np.log(odds)
print(log_odds)

[[ 0.34528022 -0.80234647  0.38938531 -0.41058021]
 [ 0.2550834  -0.25947973  0.07447203 -0.1500526 ]
 [ 0.33594152 -0.83133191  0.50130974 -0.66476999]
 [ 0.18757551 -0.59855559  0.0549448   0.17192727]]
